name: Main
on: push
jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
  test:
    name: Run unit tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift test
